FROM mcr.microsoft.com/devcontainers/typescript-node:20-bullseye

RUN npm install -g aws-cdk

RUN curl -sSL https://install.python-poetry.org | python3 -
# RUN  poetry config virtualenvs.in-project true